version: "3.4"

services:
  airflow:
    image: apache/airflow:slim-2.5.1-python3.10
    container_name: airflow
    command: standalone
    ports:
      - 8080:8080
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/health"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always
    environment:
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "password"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      SQLALCHEMY_SILENCE_UBER_WARNING: "1"

  minio:
    image: minio/minio:RELEASE.2023-01-20T02-05-44Z
    container_name: minio
    command: [ "server", "/data", "--console-address", ":9001" ]
    ports:
      - 9001:9001 # Console
      - 9000:9000 # API
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password

  minio-mc:
    image: minio/mc:RELEASE.2023-01-11T03-14-16Z
    depends_on:
      - minio
    container_name: minio-mc
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo 'Waiting...' && sleep 1; done; /usr/bin/mc rm -r --force minio/warehouse; /usr/bin/mc mb minio/warehouse; /usr/bin/mc policy set public minio/warehouse; exit 0; "

  iceberg-catalog:
    image: tabulario/iceberg-rest:0.2.0
    depends_on:
      - minio-mc
    container_name: iceberg-catalog
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3a://warehouse
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000

  iceberg-spark:
    image: tabulario/spark-iceberg:3.3.1_1.1.0
    container_name: iceberg-spark
    command: notebook
    ports:
      - 8888:8888
      - 8081:8080
    build: spark/
    depends_on:
      - iceberg-catalog
    # volumes:
    #   - ./warehouse:/home/iceberg/warehouse
    #   - ./notebooks:/home/iceberg/notebooks/notebooks
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8888/api" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    links:
      - iceberg-catalog:rest
      - minio:minio
